version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/London

  - package-ecosystem: npm
    directory: /app/client
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "07:00"
      timezone: Europe/London
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: pip
    directory: /app/server
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/London
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
