"""Add user status

Revision ID: 5a35979619f8
Revises: 4fc4a8dcdf39
Create Date: 2024-07-03 12:46:25.892921

"""
from alembic import op
import sqlalchemy as sa
from api.models.user import UserStatus


# revision identifiers, used by Alembic.
revision = '5a35979619f8'
down_revision = '4fc4a8dcdf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), server_default=str(UserStatus.ACTIVE.value), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
