version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - echo "Getting ENV file from Secrets $APP_NAME-$APP_ENV-secret-core"
      - aws secretsmanager get-secret-value --region $AWS_REGION --secret-id "$APP_NAME-$APP_ENV-secret-core" --query SecretString --output text > secret-core.json
      - jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' secret-core.json > ./app/server/.env
  build:
    commands:
      - docker build --build-arg FROM="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PLATFORM_ECR_REPOSITORY:$RUNTIME_VERSION" -f ./aws/Dockerfile -t "$ECR_REPOSITORY:$ECR_TAG" .
      - docker tag "$ECR_REPOSITORY:$ECR_TAG" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$ECR_TAG"
  post_build:
    commands:
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$ECR_TAG"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$APP_NAME-$APP_ENV-app" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$ECR_TAG" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
